import { chromium } from 'playwright';
const b = await chromium.launch({headless:true});
const ctx = await b.newContext({viewport:{width:1365,height:768}});
const page = await ctx.newPage();
page.on('console', m=>{ if(m.type()==='error') console.log('PAGEERR', m.text().slice(0,200)); });
await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.__pcfGame?.state?.loaded,null,{timeout:60000});
await page.evaluate(()=>window.__pcfGame.dispatch({type:'SET_SCREEN',payload:'team_selection'}));
await page.waitForTimeout(500);
console.log('country cards', await page.locator('.map-selection__country-card').count());
await page.locator('.map-selection__country-card').first().click(); await page.waitForTimeout(500);
console.log('division cards', await page.locator('.map-selection__division-card').count());
await page.locator('.map-selection__division-card').first().click(); await page.waitForTimeout(500);
console.log('team rows', await page.locator('.team-row').count());
await page.locator('.team-row').first().click(); await page.waitForTimeout(500);
console.log('btn-start', await page.locator('.btn-start').count());
await page.locator('.btn-start').click(); await page.waitForTimeout(1000);
console.log('skip btn', await page.locator('.preseason-actions .btn-skip').count());
await page.locator('.preseason-actions .btn-skip').click().catch(e=>console.log('skip fail',e.message));
await page.waitForTimeout(2000);
console.log('screen', await page.evaluate(()=>window.__pcfGame?.state?.currentScreen));
console.log('sidebar count', await page.locator('.sidebar').count());
console.log('sidebar items', await page.locator('.sidebar__item').count());
console.log('cal item', await page.locator('.sidebar__item[data-tab="calendar"]').count());
console.log('bodytext', (await page.evaluate(()=>document.body.innerText)).slice(0,300).replace(/\n+/g,' | '));
await b.close();
